name: Beta Deploy

on:
  push:
    branches: [ main ]

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        uses: Borales/actions-yarn@v3
        with:
          cmd: install --frozen-lockfile

      - name: Build for production
        uses: Borales/actions-yarn@v3
        with:
          cmd: yarn
          cmd: yarn build
      
      - run: yarn
      - run: yarn build

      - name: Deploy Gh-Pages ðŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.168node.com
